static:
    path: /static-page
    controller: App\Controller\StaticPage\StaticPageController
how-it-works:
    path: /comment-ca-marche
    controller: App\Controller\StaticPage\HowItWorksPageController

pantheon:
    path: /pantheon
    controller: App\Controller\Category\PantheonController

### Ajax ###
ajax.universe.create:
    path: /ajax/get-parent/{universe}
    controller: App\Controller\Ajax\PostListController
ajax.tag.link:
    path: /ajax/get-tags/{category}/{type}
    controller: App\Controller\Ajax\Admin\TagListController
ajax.review.rate.update:
    path: /ajax/get-rates/{universe}
    controller: App\Controller\Ajax\ReviewUpdateController
### Ajax ###

### Universe ###
universe.create:
    path: /{universe}/create
    controller: App\Controller\Universe\PostCreateController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|technologie|geekerie
universe.category.create:
    path: /ecrire-un-{category}
    controller: App\Controller\Universe\PostCreateController
    requirements:
        category: news|avis|astuces
games.category.create:
    path: /{universe}/{category}/create
    controller: App\Controller\Universe\PostCreateController
    requirements:
        universe: jeux
        category: astuces
books.category.create:
    path: /{universe}/{category}/create
    controller: App\Controller\Universe\PostCreateController
    requirements:
        universe: livres
        category: fanfics|histoires
technology.category.create:
    path: /{universe}/{category}/create
    controller: App\Controller\Universe\PostCreateController
    requirements:
        universe: technologie
        category: high-tech|apps|softwares|hardware
universe.tops.type:
    path: /{universe}/tops/{type}
    controller: App\Controller\Universe\Tops\TopsController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
    defaults:
        category: 'tops'
universe:
    path: /{universe}
    controller: App\Controller\Universe\MainPageController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|technologie|geekerie|index-card|personnages|joueurs
    defaults:
        universe: jeux

universe.category:
    path: /{universe}/{category}/{page}
    controller: App\Controller\Universe\CategoryController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|geekerie
        category: liste|news|tops|avis|astuces
    defaults:
        page: 1
books.category:
    path: /livres/{category}/{page}
    controller: App\Controller\Universe\CategoryController
    requirements:
        category: histoires|fanfics
    defaults:
        universe: 'livres'
        page: 1

technology:
    path: /{universe}/{category}
    controller: App\Controller\Universe\CategoryController
    requirements:
        universe: technologie
        category: high-tech|apps|softwares|hardware
    defaults:
        page: 1

universe.upvote:
    path: /{universe}/upvote/{id}
    controller: App\Controller\Universe\Upvote\UpvoteController::upvote
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
universe.downvote:
    path: /{universe}/downvote/{id}
    controller: App\Controller\Universe\Upvote\UpvoteController::downvote
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe

universe.favorite.add:
    path: /favorite/add/{id}
    controller: App\Controller\Universe\Favorite\FavoriteController::add
universe.favorite.remove:
    path: /favorite/remove/{id}
    controller: App\Controller\Universe\Favorite\FavoriteController::remove
### Universe ###


### HUB ###
hub.category:
    path: /hub/{category}
    controller: App\Controller\Hub\CategoryController
    requirements:
        category: lives|histoires|fanfics|illustrations|fanart|cosplay|videos
### HUB ###


### Registration ###
user.registration:
    path: /registration
    controller: App\Action\User\Registration\RegistrationAction
user.verify:
    path: /confirm/{token}
    controller: App\Controller\User\Registration\EmailVerifyController
### Registration ###


### Login ###
app_login:
    path: /login
    controller: App\Action\User\Authorization\LoginAction
user.login.force:
    path: /login/force
    controller: App\Action\User\Authorization\ForceLoginAction
app_logout:
    path: /logout
    controller: App\Controller\User\SecurityController::logout
### Login ###


### Builder ###
user.profile.builder:
    path: /aventurier/armurerie
    controller: App\Controller\User\Avatar\AvatarBuilderController
user.profile.avatar.build:
    path: /aventurier/avatar/build
    controller: App\Action\User\Avatar\BuildAction

user.profile.background:
    path: /aventurier/background/update
    controller: App\Action\User\Avatar\BackgroundUpdateAction
user.profile.background.upload:
    path: /aventurier/background/upload
    controller: App\Action\User\Avatar\BackgroundUploadAction

user.profile.background.remove:
    path: /aventurier/background/remove/{id}
    controller: App\Action\User\Avatar\RemoveBackgroundAction
### Builder ###


### Settings ###
user.settings:
    path: /aventurier/parametres/
    controller: App\Controller\User\Settings\SettingsController
user.update.biography:
    path: /aventurier/update/biography
    controller: App\Action\User\Settings\BiographyUpdateAction
user.update.settings:
    path: /aventurier/update/settings
    controller: App\Action\User\Settings\SettingsAction
user.update.userInfo:
    path: /aventurier/update/user-info
    controller: App\Action\User\Settings\UserInfoAction

user.recovery.send.mail:
    path: /recovery/send-mail
    controller: App\Action\User\Settings\PasswordRecovery\SendRecoveryMailAction
user.password.recovery:
    path: /recovery/{token}
    controller: App\Controller\User\Settings\PasswordRecoveryController
user.password.recovery.check:
    path: /recovery/check/{token}
    controller: App\Action\User\Recovery\PasswordRecoveryAction
### Settings ###


### Chat ###
chat.reply:
    path: /chat/reply/{chatId}
    controller: App\Action\User\Chat\ChatReplyAction
    methods: 'POST'
    defaults:
        chatId: null
chat.update:
    path: /chat/update/{chatId}
    controller: App\Action\User\Chat\ChatUpdateAction
    methods: 'GET'
chat.messages:
    path: /chat/messages/{chatId}
    controller: App\Action\User\Chat\ChatMessagesAction
    methods: 'GET'
chat.create:
    path: /chat/create
    controller: App\Action\User\Chat\AddChatAction
chat.create.by.login:
    path: /chat/create/{login}
    controller: App\Action\User\Chat\CreateChatByLoginAction
chat.delete:
    path: /chat/delete/{chatId}
    controller: App\Action\User\Chat\DeleteChatAction
chat.info:
    path: /chat/info/{chatId}
    controller: App\Action\User\Chat\ChatInfoAction

user.profile.message:
    path: /aventurier/message
    controller: App\Controller\User\Message\MessageController
### Chat ###


### SocialWeb ###
user.login.facebook:
    path: /connect/facebook
    controller: App\Controller\User\SocialWeb\FacebookController::connectAction
user.login.check.facebook:
    path: /connect/facebook/check/
    controller: App\Controller\User\SocialWeb\FacebookController::connectCheckAction
    schemes:    [https]

user.login.google:
    path: /connect/google
    controller: App\Controller\User\SocialWeb\GoogleController::connectAction
user.login.check.google:
    path: /connect/google/check/
    controller: App\Controller\User\SocialWeb\GoogleController::connectCheckAction
    schemes:    [https]

user.login.discord:
    path: /connect/discord
    controller: App\Controller\User\SocialWeb\DiscordController::connectAction
user.login.check.discord:
    path: /connect/discord/check/
    controller: App\Controller\User\SocialWeb\DiscordController::connectCheckAction
    schemes:    [https]

user.login.twitch:
    path: /connect/twitch
    controller: App\Controller\User\SocialWeb\TwitchController::connectAction
user.login.check.twitch:
    path: /connect/twitch/check/
    controller: App\Controller\User\SocialWeb\TwitchController::connectCheckAction
    schemes:    [https]

user.login.steam:
    path: /connect/steam
    controller: App\Controller\User\SocialWeb\SteamController::connectAction
user.login.check.steam:
    path: /connect/steam/check/
    controller: App\Controller\User\SocialWeb\SteamController::connectCheckAction
    schemes:    [https]

user.login.twitter:
    path: /connect/twitter
    controller: App\Controller\User\SocialWeb\TwitterController::connectAction
user.login.check.twitter:
    path: /connect/twitter/check/
    controller: App\Controller\User\SocialWeb\TwitterController::connectCheckAction

user.unlink.socialWeb:
    path: /unlink/{socialWeb}
    controller: App\Action\User\Settings\SocialWebUnlinkAction
user.update.socialWeb:
    path: /update/{socialWeb}
    controller: App\Action\User\Settings\SocialWebUpdateAction

user.email.set:
    path: /aventurier/email/set
    controller: App\Controller\User\SetEmailController
user.email.check:
    path: /aventurier/email/check
    controller: App\Action\User\CheckEmailAction
### SocialWeb ###


user.profile.pages:
    path: /aventurier/{page}
    controller: App\Controller\User\Profile\ProfilePagesController
    requirements:
        page: brouillons|creations|quetes|favoris|details|listes

### Profile ###
user.follow:
    path: /aventurier/follow/{login}
    controller: App\Action\User\FollowUser\FollowAction
user.unfollow:
    path: /aventurier/unfollow/{login}
    controller: App\Action\User\FollowUser\UnfollowAction

user.reputation.up:
    path: /aventurier/reputation-up/{login}
    controller: App\Action\User\Reputation\ReputationUpAction

user.profile.notifications:
    path: /aventurier/notifications
    controller: App\Controller\User\Notifications\NotificationsController
user.profile.wall:
    path: /aventurier/mur
    controller: App\Controller\User\Wall\WallController

user.profile:
    path: /aventurier/{login}
    controller: App\Controller\User\Profile\ProfileController
user.my.profile:
    path: /aventurier/
    controller: App\Controller\User\Profile\MyProfileController
### Profile ###

### POST ###
post.add:
    path: /{universe}/{type}/save
    controller: App\Controller\Post\SaveController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|technologie|geekerie
post.indexCard:
    path: /{universe}/index-card/view/{id}-{meta}
    controller: App\Controller\Universe\CategoryController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|manga|comics|bd
    defaults:
        meta: 'post-meta'
        page: 1
        category: 'index-card'
post.indexCard.category:
    path: /{universe}/{id}-{meta}/{category}/
    controller: App\Controller\Universe\CategoryController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|manga|comics|bd
        category: wiki|joueurs|media|discussions|personnages|avis|tops
    defaults:
        meta: 'post-meta'
        page: 1
post.indexCard.category.item:
    path: /{universe}/{id}-{meta}/{category}/{post_id}-{post_meta}
    controller: App\Controller\Universe\CategoryArticleController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe|manga|comics|bd
        category: wiki|avis|news|astuces|news-article|avis-article|media|wiki-article|discussions
    defaults:
        meta: 'post-meta'
        post_meta: 'post-meta'
### POST ###

### COMMENT ###
comment.like:
    path: /comment/like/{post_id}/{comment_id}
    controller: App\Controller\Comment\LikeController
### COMMENT ###

### Admin area ###
admin.login:
    path: /admin/login
    controller: App\Controller\Admin\Security\LoginController
admin.logout:
    path: /admin/logout
    controller: App\Controller\Admin\Security\LogoutController
admin.dashboard:
    path: /admin
    controller: App\Controller\Admin\Dashboard\MainController

admin.indexCards.list:
    path: /admin/{universe}/list
    controller: App\Controller\Admin\Post\IndexCards\ListController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
admin.indexCards.view:
    path: /admin/{universe}/view/{id}
    controller: App\Controller\Admin\Post\IndexCards\ViewController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
admin.indexCards.form:
    path: /admin/{universe}/form/{id}
    controller: App\Controller\Admin\Post\IndexCards\FormController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
    defaults:
        id: 0
admin.indexCards.delete:
    path: /admin/{universe}/delete/{id}
    controller: App\Controller\Admin\Post\IndexCards\DeleteController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe

admin.indexCards.attributes.link:
    path: /admin/{universe}/attributes/{type}/link/{id}
    controller: App\Controller\Admin\Post\Attributes\LinkController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
admin.indexCards.attributes.unlink:
    path: /admin/unlink/attribute/{post_id}/{id}
    controller: App\Controller\Admin\Post\Attributes\UnlinkController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
admin.indexCards.attributes.list:
    path: /admin/{universe}/attributes/{type}/list
    controller: App\Controller\Admin\Post\Attributes\ListController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
admin.indexCards.attributes.form:
    path: /admin/{universe}/attributes/{type}/form/{id}
    controller: App\Controller\Admin\Post\Attributes\FormController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
    defaults:
        id: 0
admin.indexCards.attributes.form.update:
    path: /admin/{universe}/attributes/{type}/form/update/{id}
    controller: App\Controller\Admin\Post\Attributes\UpdateFormController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe
    defaults:
        id: 0
admin.indexCards.attributes.delete:
    path: /admin/{universe}/attributes/delete/{id}
    controller: App\Controller\Admin\Post\Attributes\DeleteController
    requirements:
        universe: jeux|livres|series|films|jeux-de-societe

admin.indexCards.attachments.link:
    path: /admin/{universe}/attachments/link/{id}
    controller: App\Controller\Admin\Post\Attachments\LinkController
admin.indexCards.attachments.delete:
    path: /admin/{universe}/attachments/delete/{postId}/{id}
    controller: App\Controller\Admin\Post\Attachments\DeleteController

admin.users:
    path: /admin/users
    controller: App\Controller\Admin\Users\MainController
admin.users.view:
    path: /admin/users/view/{id}
    controller: App\Controller\Admin\Users\ViewController

admin.platforms:
    path: /admin/platforms
    controller: App\Controller\Admin\Platforms\MainController
admin.platforms.view:
    path: /admin/platforms/view/{id}
    controller: App\Controller\Admin\Platforms\ViewController
admin.platforms.create:
    path: /admin/platforms/create
    controller: App\Controller\Admin\Platforms\CreateController
admin.platforms.remove:
    path: /admin/platforms/remove/{id}
    controller: App\Controller\Admin\Platforms\RemoveController
admin.platforms.attributes.create:
    path: /admin/platforms/attributes/create/{platform}
    controller: App\Controller\Admin\Platforms\Attributes\CreateController
admin.platforms.attributes.remove:
    path: /admin/platforms/attributes/remove/{id}
    controller: App\Controller\Admin\Platforms\Attributes\RemoveController
### Admin area ###


### GENERAL ###
general:
    path: /{category}
    controller: App\Controller\GeneralRoutes\GeneralController